spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 2000
            loggerLevel: BASIC
      circuitbreaker:
        enabled: true